### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by cobbinaloic** [FranciscodeMaussion/RocketBookPages#15]
I have installed everything required for the script to work but when I try 

"rocketqr create -q 5 -f A4 -t 0 -n True" 

in the Terminal, here is what comes back

"Traceback (most recent call last):
  File "/home/Loic/.local/bin/rocketqr", line 11, in <module>
    load_entry_point('rocketqr', 'console_scripts', 'rocketqr')()
  File "/home/Loic/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/Loic/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/Loic/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/Loic/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/Loic/RocketBookPages/rocketqr.py", line 67
    return f"The file {out_file} already exists"
                                               ^
SyntaxError: invalid synt"

**To Reproduce**
1. Install RocketBookPages from the instructions given
2. Go to Terminal
3. Type in "rocketqr create -q 5 -f A4 -t 0 -n True"

**Expected behavior**
I expect the pages to be generated.

**Desktop (please complete the following information):**
 - OS: MX Linux kde from mxlinux.com
 - Browser : Chromium 
 - Version 83.0.4103.116

**Comment by FranciscodeMaussion** [comment]
Hi! Thanks for using my project! You must use Python3. Obviously, I will review the issue deeply. Take into account this is a small project in which I am not working at the moment. I hope this helps.
Feel free to reopen the issue if you need it.
